services:
  my-devbox:
    init: true
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DEV_USER=${DEV_USER}
        - DEV_USER_ID=${DEV_USER_ID}
        - DEV_GROUP_ID=${DEV_GROUP_ID}
        - DEV_DOCKER_GROUP_ID=${DEV_DOCKER_GROUP_ID}
        - DEV_HOSTNAME=${DEV_HOSTNAME}
    image: local/dood-sshd
    container_name: "${DEV_USER}-dood-sshd"
    hostname: ${DEV_HOSTNAME}
    ports:
      - "${DEV_HOSTPORT}:22"
    volumes:
      - ./data:/home/${DEV_USER}/data
      - /var/run/docker.sock:/var/run/docker.sock
    stdin_open: true
    tty: true
    